version: '3.8'
services:
  app:
    build: ./hello-otel-autoinstrument
    restart: always
    ports:
      - 8081:80
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4318
  otelcol:
    image: otel/opentelemetry-collector
    container_name: otelcol
    ports:
      - 4317:4317
      - 4318:4318
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-exporter/otel-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - NEW_RELIC_LICENSE_KEY